/**
 * TanStack Router setup.
 *
 * We use file-based routes. The routeTree.gen.ts file is
 * auto-generated by the Vite plugin / CLI; we run the
 * generate script in `pnpm dev` and at build time.
 *
 * For now we set up the router manually with explicit
 * routes so we can build out the structure without waiting
 * on the codegen step.
 */

import {
  createRootRoute,
  createRoute,
  createRouter,
  Outlet,
  redirect,
} from '@tanstack/react-router';
import { RootLayout } from './layout/RootLayout';
import { OverviewPage } from '@/routes/overview/OverviewPage';
import { TrackPage } from '@/routes/track/TrackPage';
import { TrackMonthPage } from '@/routes/track/TrackMonthPage';
import { TrackAddPage } from '@/routes/track/TrackAddPage';
import { TrackTransactionPage } from '@/routes/track/TrackTransactionPage';
import { TrackCategoriesPage } from '@/routes/track/TrackCategoriesPage';
import { TrackBudgetPage } from '@/routes/track/TrackBudgetPage';
import { TrackRecurringPage } from '@/routes/track/TrackRecurringPage';
import { SplitPage } from '@/routes/split/SplitPage';
import { SplitGroupPage } from '@/routes/split/SplitGroupPage';
import { SplitGroupAddPage } from '@/routes/split/SplitGroupAddPage';
import { SplitGroupBalancesPage } from '@/routes/split/SplitGroupBalancesPage';
import { SplitGroupActivityPage } from '@/routes/split/SplitGroupActivityPage';
import { SplitGroupSettlePage } from '@/routes/split/SplitGroupSettlePage';
import { SplitGroupSettingsPage } from '@/routes/split/SplitGroupSettingsPage';
import { LendPage } from '@/routes/lend/LendPage';
import { LendPersonPage } from '@/routes/lend/LendPersonPage';
import { LendLedgerPage } from '@/routes/lend/LendLedgerPage';
import { LendAddPage } from '@/routes/lend/LendAddPage';
import { SettingsPage } from '@/routes/settings/SettingsPage';
import { PeoplePage } from '@/routes/settings/PeoplePage';
import { BackupPage } from '@/routes/settings/BackupPage';
import { SearchPage } from '@/routes/overview/SearchPage';
import { OnboardingPage } from '@/routes/OnboardingPage';
import { useAppSettings } from '@shared/settings/useSettings';

const rootRoute = createRootRoute({
  component: () => (
    <RootLayout>
      <Outlet />
    </RootLayout>
  ),
});

// Guard: redirect to onboarding if first launch.
const OnboardingGuard = ({ children }: { children: React.ReactNode }) => {
  const settings = useAppSettings();
  if (settings === undefined) return null;
  if (!settings.onboardingComplete) {
    // We can't call redirect inside render — but the route
    // beforeLoad handles this. This component is a safety net.
  }
  return <>{children}</>;
};

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  beforeLoad: () => {
    throw redirect({ to: '/overview' });
  },
});

const overviewRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/overview',
  component: OverviewPage,
});

const searchRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/search',
  component: SearchPage,
});

const trackRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/track',
  component: TrackPage,
});

const trackMonthRoute = createRoute({
  getParentRoute: () => trackRoute,
  path: 'month/$year/$month',
  component: TrackMonthPage,
});

const trackAddRoute = createRoute({
  getParentRoute: () => trackRoute,
  path: 'add',
  component: TrackAddPage,
});

const trackTransactionRoute = createRoute({
  getParentRoute: () => trackRoute,
  path: 'transaction/$transactionId',
  component: TrackTransactionPage,
});

const trackCategoriesRoute = createRoute({
  getParentRoute: () => trackRoute,
  path: 'categories',
  component: TrackCategoriesPage,
});

const trackBudgetRoute = createRoute({
  getParentRoute: () => trackRoute,
  path: 'budget',
  component: TrackBudgetPage,
});

const trackRecurringRoute = createRoute({
  getParentRoute: () => trackRoute,
  path: 'recurring',
  component: TrackRecurringPage,
});

const splitRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/split',
  component: SplitPage,
});

const splitGroupRoute = createRoute({
  getParentRoute: () => splitRoute,
  path: 'group/$groupId',
  component: SplitGroupPage,
});

const splitGroupAddRoute = createRoute({
  getParentRoute: () => splitRoute,
  path: 'group/$groupId/add',
  component: SplitGroupAddPage,
});

const splitGroupBalancesRoute = createRoute({
  getParentRoute: () => splitRoute,
  path: 'group/$groupId/balances',
  component: SplitGroupBalancesPage,
});

const splitGroupActivityRoute = createRoute({
  getParentRoute: () => splitRoute,
  path: 'group/$groupId/activity',
  component: SplitGroupActivityPage,
});

const splitGroupSettleRoute = createRoute({
  getParentRoute: () => splitRoute,
  path: 'group/$groupId/settle',
  component: SplitGroupSettlePage,
});

const splitGroupSettingsRoute = createRoute({
  getParentRoute: () => splitRoute,
  path: 'group/$groupId/settings',
  component: SplitGroupSettingsPage,
});

const lendRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/lend',
  component: LendPage,
});

const lendPersonRoute = createRoute({
  getParentRoute: () => lendRoute,
  path: 'person/$personId',
  component: LendPersonPage,
});

const lendLedgerRoute = createRoute({
  getParentRoute: () => lendRoute,
  path: 'ledger/$ledgerId',
  component: LendLedgerPage,
});

const lendAddRoute = createRoute({
  getParentRoute: () => lendRoute,
  path: 'add',
  component: LendAddPage,
});

const settingsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/settings',
  component: SettingsPage,
});

const peopleRoute = createRoute({
  getParentRoute: () => settingsRoute,
  path: 'people',
  component: PeoplePage,
});

const backupRoute = createRoute({
  getParentRoute: () => settingsRoute,
  path: 'backup',
  component: BackupPage,
});

const onboardingRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/onboarding',
  component: OnboardingPage,
});

const routeTree = rootRoute.addChildren([
  indexRoute,
  onboardingRoute,
  overviewRoute,
  searchRoute,
  trackRoute.addChildren([
    trackMonthRoute,
    trackAddRoute,
    trackTransactionRoute,
    trackCategoriesRoute,
    trackBudgetRoute,
    trackRecurringRoute,
  ]),
  splitRoute.addChildren([
    splitGroupRoute,
    splitGroupAddRoute,
    splitGroupBalancesRoute,
    splitGroupActivityRoute,
    splitGroupSettleRoute,
    splitGroupSettingsRoute,
  ]),
  lendRoute.addChildren([lendPersonRoute, lendLedgerRoute, lendAddRoute]),
  settingsRoute.addChildren([peopleRoute, backupRoute]),
]);

export const router = createRouter({
  routeTree,
  defaultPreload: 'intent',
});

// Register router types for type-safe links
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

// Suppress unused warning — OnboardingGuard is kept for future
// route-level guards even though the beforeLoad already handles
// the redirect.
void OnboardingGuard;
